# Generated by Django 4.1.2 on 2022-11-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('PhoneNo', models.CharField(max_length=20)),
                ('Role', models.CharField(choices=[('Admin', 'Admin'), ('Accountant', 'Accountant')], max_length=20)),
                ('Address', models.CharField(max_length=150)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
    ]
