# Generated by Django 4.1.2 on 2022-10-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eid', models.CharField(max_length=10)),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('PhoneNo', models.IntegerField()),
                ('Role', models.CharField(max_length=50)),
                ('Salary', models.IntegerField()),
                ('PF', models.IntegerField()),
            ],
        ),
    ]
