# Generated by Django 4.1.4 on 2022-12-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vendor_Id', models.IntegerField()),
                ('VendorName', models.CharField(max_length=50)),
                ('VendorPhoneNo', models.IntegerField()),
                ('Product', models.CharField(max_length=50)),
                ('ProductQuantity', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Total_Price', models.IntegerField()),
                ('RecivedDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vendor_Id', models.IntegerField()),
                ('VendorName', models.CharField(max_length=50)),
                ('VendorPhoneNo', models.IntegerField()),
                ('Product', models.CharField(max_length=50)),
                ('ProductQuantity', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Total_Price', models.IntegerField()),
                ('OrderedDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Phone_No', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=50)),
                ('Billing_Address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vendororder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VendorName', models.CharField(max_length=100)),
                ('Phone_No', models.IntegerField()),
                ('Product', models.CharField(max_length=150)),
                ('Product_Quantity', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Total_Price', models.IntegerField()),
                ('Ordereddate', models.DateField()),
            ],
        ),
    ]
