# Generated by Django 4.1.4 on 2022-12-07 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='OrderedDate',
            field=models.DateField(default=datetime.datetime(2022, 12, 7, 8, 56, 53, 607913)),
        ),
    ]
