# Generated by Django 4.1.4 on 2022-12-07 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0002_orders_is_deleted_alter_orders_ordereddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendororder',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='OrderedDate',
            field=models.DateField(default=datetime.datetime(2022, 12, 7, 8, 59, 36, 919400)),
        ),
        migrations.AlterField(
            model_name='vendororder',
            name='Ordereddate',
            field=models.DateField(default=datetime.datetime(2022, 12, 7, 8, 59, 36, 920399)),
        ),
    ]
