# Generated by Django 4.1 on 2022-12-07 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0003_vendororder_is_deleted_alter_orders_ordereddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='OrderedDate',
            field=models.DateField(default=datetime.datetime(2022, 12, 7, 12, 56, 38, 804772)),
        ),
        migrations.AlterField(
            model_name='vendororder',
            name='Ordereddate',
            field=models.DateField(default=datetime.datetime(2022, 12, 7, 12, 56, 38, 805771)),
        ),
    ]
