# Generated by Django 4.1.4 on 2022-12-07 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='OrderedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 16, 56, 53, 612909, tzinfo=datetime.timezone.utc)),
        ),
    ]
