# Generated by Django 4.1.4 on 2022-12-07 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0002_alter_salesorder_ordereddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='OrderedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 16, 59, 36, 924398, tzinfo=datetime.timezone.utc)),
        ),
    ]
