# Generated by Django 4.1 on 2022-12-07 20:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0004_alter_orders_ordereddate_and_more'),
        ('Sales', '0003_alter_salesorder_ordereddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesitem',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseitem', to='Purchase.vendororder'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='OrderedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 20, 56, 38, 810789, tzinfo=datetime.timezone.utc)),
        ),
    ]
