# Generated by Django 4.1.3 on 2022-12-08 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0004_alter_salesitem_stock_alter_salesorder_ordereddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='OrderedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 8, 11, 49, 22, 536943, tzinfo=datetime.timezone.utc)),
        ),
    ]
